
-- https://www.tutorialspoint.com/sql/sql-and-or-clauses.htm

show databases;

use testdb;

CREATE TABLE test(
   ID   INT              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   AGE  INT              NOT NULL,
   ADDRESS  CHAR (25) ,
   SALARY   DECIMAL (18, 2),       
   PRIMARY KEY (ID)
);

select * from test;
select * from customers;

DESC CUSTOMERS;

-- DROP TABLE test;
-- DESC test;

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'Khilan', 25, 'Delhi', 1500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'kaushik', 23, 'Kota', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Chaitali', 25, 'Mumbai', 6500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'Hardik', 27, 'Bhopal', 8500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Komal', 22, 'MP', 4500.00 );

INSERT INTO CUSTOMERS 
VALUES (7, 'Muffy', 24, 'Indore', 10000.00 );

SELECT ID, NAME, SALARY FROM CUSTOMERS;
SELECT * FROM CUSTOMERS;

SELECT ID, NAME, SALARY 
FROM CUSTOMERS
WHERE SALARY > 2000;

SELECT ID, NAME, SALARY 
FROM CUSTOMERS
WHERE NAME = 'Hardik';

SELECT ID, NAME, SALARY 
FROM CUSTOMERS
WHERE SALARY > 2000 AND age < 25;

/*
The SQL UPDATE Query is used to modify the existing records in a table. 
You can use the WHERE clause with the UPDATE query to update the selected rows, 
otherwise all the rows would be affected.
*/

UPDATE CUSTOMERS
SET ADDRESS = 'Pune'
WHERE ID = 6;

UPDATE CUSTOMERS
SET ADDRESS = 'Pune', SALARY = 1000.00;

DELETE FROM CUSTOMERS
WHERE ID = 6;

SELECT * FROM CUSTOMERS
WHERE SALARY LIKE '200%';

SELECT * FROM CUSTOMERS
LIMIT 3;

SELECT * FROM CUSTOMERS
WHERE id <= 5;

SELECT * FROM CUSTOMERS
ORDER BY NAME, SALARY;
   
SELECT * FROM CUSTOMERS
ORDER BY NAME DESC;

SELECT NAME, SUM(SALARY) FROM CUSTOMERS
GROUP BY NAME;

SELECT SALARY FROM CUSTOMERS
ORDER BY SALARY;

SELECT DISTINCT SALARY FROM CUSTOMERS
ORDER BY SALARY;

SELECT * FROM CUSTOMERS
   ORDER BY NAME DESC;

SELECT * FROM CUSTOMERS
   ORDER BY (CASE ADDRESS
   WHEN 'DELHI' 	 THEN 1
   WHEN 'BHOPAL' 	 THEN 2
   WHEN 'KOTA' 	 THEN 3
   WHEN 'AHMEDABAD' THEN 4
   WHEN 'MP' 	THEN 5
   ELSE 100 END) ASC, ADDRESS DESC;


SELECT ID, NAME, AGE, AMOUNT
   FROM CUSTOMERS, ORDERS
   WHERE  CUSTOMERS.ID = ORDERS.CUSTOMER_ID;
   

